-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM ONLINE_SALE S LEFT JOIN USER_INFO U ON S.USER_ID = U.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING U.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER
# WHERE U.GENDER IS NOT NULL
