-- 코드를 입력하세요
SELECT H.CAR_ID, P.CAR_TYPE, TRUNCATE(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON C.CAR_TYPE = P.CAR_TYPE
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND P.DURATION_TYPE LIKE '30%' 
    AND (ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) BETWEEN 500000 AND 2000000 - 1)
    AND C.CAR_ID NOT IN ( 
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01')
GROUP BY CAR_ID, CAR_TYPE, FEE
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC