-- 코드를 작성해주세요
SELECT CONVERT(E2.YEAR,SIGNED) AS YEAR, E2.MAX_SIZE - E1.SIZE_OF_COLONY AS YEAR_DEV, E1.ID
FROM ECOLI_DATA E1 JOIN (
                    SELECT DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
                    FROM ECOLI_DATA
                    GROUP BY DATE_FORMAT(DIFFERENTIATION_DATE, '%Y')
                ) E2 ON DATE_FORMAT(E1.DIFFERENTIATION_DATE, '%Y') = E2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC
