-- 코드를 작성해주세요
SELECT I.ID, II.FISH_NAME, II.LENGTH
FROM FISH_INFO I 
    JOIN (SELECT NI.FISH_TYPE, NI.FISH_NAME, ML.LENGTH
            FROM (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
                FROM FISH_INFO 
                GROUP BY FISH_TYPE) ML 
                JOIN FISH_NAME_INFO NI 
                ON ML.FISH_TYPE = NI.FISH_TYPE) II
    ON I.FISH_TYPE = II.FISH_TYPE AND I.LENGTH = II.LENGTH
ORDER BY I.ID ASC
            
            
